# 异常表和本地变量个数

try..catch 即使有多个catch子句，当抛出异常时，只会进入其中一个，所以只会有一个变量。

每个实例方法，至少会有一个参数，第一个参数就是this，即对当前对象的引用，由JVM运行时自动传入。

## exception_table
start_pc 和 end_pc 表示 从 start_pc 到 end_pc （包含start_pc，不包含end_pc）的字节码间，如果抛出异常，
由对应的 catch_type 的 handler_pc 处的代码处理。


所谓的：无论是否抛出异常，finally语句都会执行，在字节码层面就是把 finally 语句复制，分别粘贴到 try 语句后面，以及每个 catch 语句后面。

对于没有 catch 到的异常，编译器生成了一个 catch 任何类型 的异常的语句块，该语句块先保存异常，接着执行finally语句块的代码，然后重新抛出保存的异常对象。

方法声明上的 throws 异常列表，在生成的字节码中，有一个和 Code 平级的 Exceptions 属性
```text
Exceptions_attribute {
  u2 attribute_name_name_index; // SourceFile
  u4 attribute_length;
  u2 number_of_exceptions;
  u2 exception_index_table[number_of_exceptions];
}
```

方法声明了多少个异常，按顺序罗列在 异常属性 Exceptions_attribute 中。
